telegram-bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}
  path: https://ig10q8-188-126-45-46.ru.tuna.am # use tuna/ngrok example: https://va7k7g-188-126-45-46.ru.tuna.am

# DB tutor-bot
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# ДОБАВИЛ НОВОЕ кроме порта 8080
  #admin:
  #chat-id: "-1002898701641" # ID админ-чата (обязательно в кавычках)

# Конфигурация крипто-кошельков
crypto:
  wallets:
    - currency: USDT
      walletAddress: "0xYourEthereumAddress1"
      qrCodePath: "/qr/usdt1.png"
    - currency: ETH
      walletAddress: "0xYourEthereumAddress2"
      qrCodePath: "/qr/usdt2.png"
    - currency: BTC
      walletAddress: "1YourBitcoinAddress"
      qrCodePath: "/qr/btc.png"

# Заглушка для тестирования
vpn:
  config:
    stub-url: "https://example.com/vpn-config-stub.conf"

server:
  port: 8080
logging:
  level:
    org.springframework:
      DEBUG